// Shape of a player returned by the backend's findUndervaluedPlayers endpoint.
// Mirrors the Prisma `PlayerStats` model, minus the `playerInfo` relation
// (not included in the query) and with Decimal fields serialized to string over JSON.
export type PlayerStatsObject = {
    id: string;
    playerId: string;
    season: string;
    seasonType: string;
    playerName: string;
    nickname: string;
    teamId: string;
    teamAbbreviation: string;
    teamCount: number;
    age: number;
    gp: number;
    w: number;
    l: number;
    wPct: string;
    min: string;
    fgm: string;
    fga: string;
    fgPct: string;
    fg3m: string;
    fg3a: string;
    fg3Pct: string;
    ftm: string;
    fta: string;
    ftPct: string;
    oreb: string;
    dreb: string;
    reb: string;
    ast: string;
    tov: string;
    stl: string;
    blk: string;
    blka: string;
    pf: string;
    pfd: string;
    pts: string;
    plusMinus: string;
    nbaFantasyPts: string;
    wnbaFantasyPts: string;
    dd2: number;
    td3: number;
    gpRank: number;
    wRank: number;
    lRank: number;
    wPctRank: number;
    minRank: number;
    fgmRank: number;
    fgaRank: number;
    fgPctRank: number;
    fg3mRank: number;
    fg3aRank: number;
    fg3PctRank: number;
    ftmRank: number;
    ftaRank: number;
    ftPctRank: number;
    orebRank: number;
    drebRank: number;
    rebRank: number;
    astRank: number;
    tovRank: number;
    stlRank: number;
    blkRank: number;
    blkaRank: number;
    pfRank: number;
    pfdRank: number;
    ptsRank: number;
    plusMinusRank: number;
    nbaFantasyPtsRank: number;
    wnbaFantasyPtsRank: number;
    dd2Rank: number;
    td3Rank: number;
};

export type PlayerGameLogObject = {
    id: string;
    seasonId: string;
    season: string;
    seasonType: string;
    playerId: string;
    playerName: string;
    teamId: string;
    teamAbbreviation: string;
    teamName: string;
    gameId: string;
    gameDate: string;
    matchup: string;
    wl: string;
    min: number;
    fgm: number;
    fga: number;
    fgPct: string;
    fg3m: number;
    fg3a: number;
    fg3Pct: string;
    ftm: number;
    fta: number;
    ftPct: string;
    oreb: number;
    dreb: number;
    reb: number;
    ast: number;
    stl: number;
    blk: number;
    tov: number;
    pf: number;
    pts: number;
    plusMinus: string;
    fantasyPts: string;
    videoAvailable: number;
    ptsMatch: boolean;
    astMatch: boolean;
    rebMatch: boolean;
    ptsStdDeviation: string;
    matchCount: number;
};

export type PlayerObject = {
    playerName: string;
    count: number;
    stats: PlayerStatsObject;
    player_game_logs: PlayerGameLogObject[];
}

